SELECT
    IDXS.TABLENAME  AS TABLE_NAME
,   IDXS.INDEXNAME  AS INDEX_NAME
,   IDX.INDISUNIQUE AS UNIQUENESS
,   COL.COLUMN_NAME AS COLUMN_NAME
,   IDX.POSITION    AS POSITION
 FROM
    PG_INDEXES IDXS,
    (SELECT
        IDX.INDEXRELID                      AS INDEXRELID
    ,   IDX.INDISUNIQUE                     AS INDISUNIQUE
    ,   UNNEST(IDX.INDKEY)                  AS INDKEY
    ,   GENERATE_SUBSCRIPTS(IDX.INDKEY,1)   AS POSITION
    FROM
        PG_INDEX IDX
    ) IDX
    ,INFORMATION_SCHEMA.COLUMNS COL
WHERE
    IDXS.SCHEMANAME         = current_schema
AND IDXS.INDEXNAME          NOT LIKE '%pg_toast_%'
AND IDX.INDEXRELID          = IDXS.INDEXNAME::regclass
AND COL.TABLE_SCHEMA        = current_schema
AND COL.TABLE_NAME          = IDXS.TABLENAME
AND IDXS.TABLENAME          = '<?= $tableName;?>'
AND COL.ORDINAL_POSITION    = IDX.INDKEY
ORDER BY
    IDXS.TABLENAME
,   IDXS.INDEXNAME
,   IDX.POSITION
